* Deep convolutional tensor network

** What is this?

This is the code I used to perform experiments in
[[https://arxiv.org/abs/2005.14506][Deep convolutional tensor network (arxiv:2005.14506)]].

** How to run an experiment

The main entry point is [[./new_runner.py]]. To see help about its arguments, run
#+begin_src
PYTHONPATH=. python new_runner.py --help
#+end_src
or read all the decorators of =main= function in [[./new_runner.py]].

An example of how to run training is

#+begin_src
$ PYTHONPATH=. python new_runner.py \
  --ds-path /path/to/downloaded/fashionmnist \
  --ds-type fashionmnist \
  --experiments-dir /path/to/where/experiments/info/will/be/saved \
  --epses-specs '(4,4),(3,6)' \
  --batch-size 128 \
  --optimizer adam \
  --reg-type epses_composition \
  --reg-coeff 1e-2 \
  --init-epses-composition-unit-empirical-output-std \
  --lr 1.11e-4
#+end_src

The flag =--init-epses-composition-unit-empirical-output-std= turns on
"empirical unit std of intermediate representations initialization", as it's called in the
article. You can pass the flag =--init-epses-composition-unit-theoretical-output-std= instead
to use /He initialization/.

The code base is full of old code which I don't use anymore. Unfortunately, I don't have time
to clean it up for public use. So I suggest you look at [[./new_runner.py]] and at code it uses,
but ignore code it doesn't use.

** How to run tests in parallel

#+BEGIN_SRC
$ conda install pytest-xdist # from conda-forge
$ cd ~/projects/dctn
$ python -m pytest --numprocesses=4 tests/
#+END_SRC

** Various notes and plots

Another thing you, dear reader, might be interested in are various plots and small notes
exploring how hyperparameters affect everything. They are located in
[[./small_experiments/plots]]. Plots are in HTML files generated by Bokeh. You can't view them on
github, you need to download them. Whenever a directory there contains files, the names of
which start with /01/, /02/, etc., you should probably look at them in that order. Sometimes
the filenames tell you what this is about. Sometimes the HTML files containing the plots
contain descriptions of what the plots show. Also, in HTML files you can see parameters passed
to [[./new_runner.py]], which contain hyperparameters. All this is very raw and probably not very
readable, sorry about that. I made them primarily for myself.
